#!/usr/bin/env bash
#
# Regenerate backend/requirements-desktop.lock — the pinned dependency set the
# desktop (PyInstaller) build installs from (see ../build-desktop.sh).
#
# Run this after changing [project] dependencies in pyproject.toml, commit the
# result. It resolves in a throwaway venv so dev-only extras (pytest, ruff,
# psycopg) never leak into the desktop binary.
#
# Note: pip resolves for the platform it runs on. The only platform-conditional
# dependency in this stack is PyInstaller's macholib (darwin-only), which is
# appended below with an explicit marker so the lockfile works on macOS even
# when regenerated on Linux (CI).
#
# Usage:  ./scripts/regen-desktop-lock.sh   (from backend/, any cwd works)
set -euo pipefail

BACKEND="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="${PYTHON:-python3.12}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

"$PY" -m venv "$TMP/venv"
"$TMP/venv/bin/pip" install -q --upgrade pip
"$TMP/venv/bin/pip" install -q "$BACKEND[desktop]"

{
  echo "# Pinned dependencies for the desktop (PyInstaller) build."
  echo "# Generated by backend/scripts/regen-desktop-lock.sh — do not edit by hand."
  echo "# Version floors live in pyproject.toml; this file freezes one resolution"
  echo "# of them so desktop builds are reproducible (T11)."
  "$TMP/venv/bin/pip" freeze --exclude pmomentum-backend | grep -v '^macholib=='
  # PyInstaller's darwin-only dep: not present in a Linux-generated freeze, but
  # required when the desktop build runs on macOS. Pinned with a marker so the
  # same lockfile installs cleanly on both platforms.
  echo 'macholib==1.16.3 ; sys_platform == "darwin"'
} > "$BACKEND/requirements-desktop.lock"

echo "Wrote $BACKEND/requirements-desktop.lock"
